### ISSUE TITLE
Hi Mattieu

### ISSUE THREAD

**Issue by mjdunther** [MatthieuBOUCHET/PythonMETAR#3]
Hi
Matthieu are you okay?

My name is Moisés and I'm from Sao Paulo - Brazil.
I'm new to python. I've been studying for 3 months.
I would like to congratulate you for your PythonMETAR module. It is very important for anyone who does flight simulation like me on Xplane.
I made an application using your PythonMETAR module and would like to know if you authorize me to make this application available on xplane.org and GitHub by providing your credits for free to other xplane users.
Thank you very much.

Moisés.

**Comment by MatthieuBOUCHET** [comment]
Hi, sorry for my (extreme !) late answer. I hope that you publish your application. For sure, you can. 
Regards,
M.B
